INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Ana Santos', 'anasantos@example.com', '44444444444');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Ana Santos', 'anasantos@email.com', '44444444445');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('João Silva', 'joao@example.com', '55555555555');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Maria Souza', 'maria@example.com', '66666666666');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Lucas Oliveira', 'lucas@example.com', '77777777777');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Julia Pereira', 'julia@example.com', '88888888888');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Pedro Rodrigues', 'pedro@example.com', '99999999999');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Sofia Almeida', 'sofia@example.com', '11111111111');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Matheus Lima', 'matheus@example.com', '22222222222');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Isabella Gonçalves', 'isabella@example.com', '33333333333');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Arthur Carvalho', 'arthur@example.com', '12345678901');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Lara Fernandes', 'lara@example.com', '23456789012');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Davi Ribeiro', 'davi@example.com', '34567890123');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Mariana Torres', 'mariana@example.com', '45678901234');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Thiago Santos', 'thiago@example.com', '56789012345');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Helena Silva', 'helena@example.com', '67890123456');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Enzo Souza', 'enzo@example.com', '78901234567');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Valentina Oliveira', 'valentina@example.com', '89012345678');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Benjamin Pereira', 'benjamin@example.com', '90123456789');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Laura Rodrigues', 'laura@example.com', '01234567890');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Gabriel Almeida', 'gabriel@example.com', '00000000001');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Manuela Lima', 'manuela@example.com', '00000000002');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Nicolas Gonçalves', 'nicolas@example.com', '00000000003');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Lorena Carvalho', 'lorena@example.com', '00000000004');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Rafaela Fernandes', 'rafaela@example.com', '00000000005');
INSERT INTO Cliente (nome_cliente, email, cpf) VALUES ('Gustavo Ribeiro', 'gustavo@example.com', '00000000006');

INSERT INTO Aluguel (id_locacao, data_vencimento, valor_pago, data_pagamento, obs) VALUES (1, '2023-11-10', 400, null, "observacao 1");
INSERT INTO Aluguel (id_locacao, data_vencimento, valor_pago, data_pagamento, obs) VALUES (2, '2023-11-11', 500, null, "observacao 2");
INSERT INTO Aluguel (id_locacao, data_vencimento, valor_pago, data_pagamento, obs) VALUES (3, '2023-11-12', 600, null, "observacao 3");
INSERT INTO Aluguel (id_locacao, data_vencimento, valor_pago, data_pagamento, obs) VALUES (4, '2023-11-13', 700, null, "observacao 4");
INSERT INTO Aluguel (id_locacao, data_vencimento, valor_pago, data_pagamento, obs) VALUES (5, '2023-11-14', 800, null, "observacao 5");
INSERT INTO Aluguel (id_locacao, data_vencimento, valor_pago, data_pagamento, obs) VALUES (6, '2023-11-15', 900, null, "observacao 6");
INSERT INTO Aluguel (id_locacao, data_vencimento, valor_pago, data_pagamento, obs) VALUES (7, '2023-11-16', 1000, null, "observacao 7");
INSERT INTO Aluguel (id_locacao, data_vencimento, valor_pago, data_pagamento, obs) VALUES (8, '2023-11-17', 1100, null, "observacao 8");
INSERT INTO Aluguel (id_locacao, data_vencimento, valor_pago, data_pagamento, obs) VALUES (9, '2023-11-18', 1200, null, "observacao 9");
INSERT INTO Aluguel (id_locacao, data_vencimento, valor_pago, data_pagamento, obs) VALUES (10, '2023-11-19', 1300, null, "observacao 10");